# Generated by Django 2.2.11 on 2020-06-08 06:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_card', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=8, message='Input 8 digit card number')])),
                ('pin', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(limit_value=4, message='Input 4 digit pin')])),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.UserATM')),
            ],
        ),
    ]
