# Generated by Django 2.2.11 on 2020-06-08 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200608_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useratm',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
